CREATE TABLE [dbo].[Member]
(
	[RSOMemberID] int IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [RSOID] INT NOT NULL , 
    [UserID] UNIQUEIDENTIFIER NOT NULL , 
    [JoinDate] DATETIME NOT NULL, 
    CONSTRAINT [FK_Member_User] FOREIGN KEY ([UserID]) REFERENCES [User]([UserID]), 
    CONSTRAINT [FK_Member_RSO] FOREIGN KEY ([RSOID]) REFERENCES [RSO]([RSOID])
)
